name: buildapp

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Up flutter
        uses: subosito/flutter-action@v1

      - name: Get flutter dependencies
        run: flutter pub get

      - name: Build apk
        run: flutter build apk --release

      - name: Create release and copy apk
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}